"""
Stochastic freight ETA handling and robust maintenance-window selection.

Specification Section 4.2 "Tactical & Dynamic Horizon (Weekly to Daily)":
    "To handle the profound volatility of goods train forecasts, the optimizer
     transitions from deterministic to Stochastic Integer Programming. The
     algorithm does not assume a single, fixed arrival time for freight trains.
     Instead, it utilizes a probabilistic distribution of ETAs generated by
     historical variance analysis. The optimization engine searches for
     maintenance block windows that are robust — meaning the selected time slot
     has a high mathematical probability of remaining clash-free even if the
     surrounding freight trains are delayed by several hours."

What this module provides:
  1. ``FreightETADistribution``   — per-train ETA distribution derived from
     historical variance analysis (falling back to IR-category priors).
  2. ``FreightScenarioSet``       — stratified/antithetic Monte-Carlo scenarios.
  3. ``RobustWindowEvaluator``    — clash-free probability, expected delay and
     CVaR for a candidate maintenance window.
  4. ``StochasticScheduleAnalyzer`` — replays a whole schedule across scenarios.
  5. ``RobustWindowOptimizer``    — integer start-time search that maximises
     robustness, i.e. the stochastic integer programming step.

Everything is deterministic given a seed: identical inputs produce identical
scenarios and therefore identical recommendations.
"""

from __future__ import annotations

import math
import random
import statistics
from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

from src.data_pipeline.models import Scenario, Train

# --- IR category priors (hours) --------------------------------------------
# Freight does not run to a fixed immutable timetable; passenger services do.
DEFAULT_FREIGHT_DELAY_MEAN_HOURS: float = 0.75   # ~45 min, per IR pilot study
DEFAULT_FREIGHT_DELAY_STD_HOURS: float = 1.0
DEFAULT_PASSENGER_DELAY_MEAN_HOURS: float = 0.05
DEFAULT_PASSENGER_DELAY_STD_HOURS: float = 0.15

# Robustness gate: a window below this clash-free probability is not acceptable.
DEFAULT_CONFIDENCE_LEVEL: float = 0.90
# Tail risk measure level for Conditional Value-at-Risk of delay.
DEFAULT_CVAR_ALPHA: float = 0.90


def _is_freight(train: Train) -> bool:
    return str(train.category).strip().lower() == "freight"


def _clamp_non_negative(value: float) -> float:
    return max(0.0, float(value))


# ---------------------------------------------------------------------------
# 1. ETA distribution
# ---------------------------------------------------------------------------
@dataclass
class FreightETADistribution:
    """
    Delay distribution for a single train.

    Built from historical observations where available; otherwise from the
    category prior. Delays are modelled as a truncated (non-negative) normal,
    which is the standard first-order description of freight arrival variance
    and keeps the scenario generator cheap enough to run per re-optimisation.
    """

    train_id: str
    category: str
    scheduled_start: float
    scheduled_end: float
    mean_delay_hours: float
    std_delay_hours: float
    sample_count: int = 0
    source: str = "prior"

    @classmethod
    def from_history(
        cls,
        train: Train,
        observations: Optional[Sequence[float]] = None,
    ) -> "FreightETADistribution":
        """
        Fit from historical delay observations (hours, relative to schedule).

        When fewer than two observations exist the category prior is used, and
        ``source`` records which one was applied so callers can tell a measured
        distribution from an assumed one.
        """
        clean = [float(o) for o in (observations or []) if o is not None]
        if len(clean) >= 2:
            return cls(
                train_id=train.id,
                category=train.category,
                scheduled_start=float(train.scheduled_start),
                scheduled_end=float(train.scheduled_end),
                mean_delay_hours=round(statistics.fmean(clean), 4),
                std_delay_hours=round(max(0.01, statistics.pstdev(clean)), 4),
                sample_count=len(clean),
                source="historical",
            )
        return cls.from_prior(train)

    @classmethod
    def from_prior(cls, train: Train) -> "FreightETADistribution":
        freight = _is_freight(train)
        mean = (
            DEFAULT_FREIGHT_DELAY_MEAN_HOURS
            if freight
            else DEFAULT_PASSENGER_DELAY_MEAN_HOURS
        )
        std = (
            DEFAULT_FREIGHT_DELAY_STD_HOURS
            if freight
            else DEFAULT_PASSENGER_DELAY_STD_HOURS
        )
        return cls(
            train_id=train.id,
            category=train.category,
            scheduled_start=float(train.scheduled_start),
            scheduled_end=float(train.scheduled_end),
            mean_delay_hours=mean,
            std_delay_hours=std,
            sample_count=0,
            source="prior",
        )

    def sample_delay(self, rng: random.Random) -> float:
        """Truncated-normal draw; delays are never negative."""
        return _clamp_non_negative(rng.gauss(self.mean_delay_hours, self.std_delay_hours))

    def quantile_delay(self, p: float) -> float:
        """Inverse CDF of the normal approximation, truncated at zero."""
        p = min(0.999, max(0.001, p))
        # Acklam-style rational approximation is overkill; use the Beasley-Springer
        # style z via the inverse error function available in the stdlib.
        z = math.sqrt(2.0) * _erfinv(2.0 * p - 1.0)
        return _clamp_non_negative(self.mean_delay_hours + z * self.std_delay_hours)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "train_id": self.train_id,
            "category": self.category,
            "scheduled_start": self.scheduled_start,
            "scheduled_end": self.scheduled_end,
            "mean_delay_hours": round(self.mean_delay_hours, 4),
            "std_delay_hours": round(self.std_delay_hours, 4),
            "sample_count": self.sample_count,
            "source": self.source,
        }


def _erfinv(x: float) -> float:
    """Winitzki's cheap approximation of the inverse error function."""
    a = 0.147
    x = max(-0.99999, min(0.99999, x))
    ln1mx2 = math.log(1.0 - x * x)
    term1 = 2.0 / (math.pi * a) + ln1mx2 / 2.0
    return math.copysign(math.sqrt(math.sqrt(term1 * term1 - ln1mx2 / a) - term1), x)


# ---------------------------------------------------------------------------
# 2. Scenario set
# ---------------------------------------------------------------------------
@dataclass
class FreightScenario:
    """One realisation of the world: per-train delay in hours."""

    index: int
    weight: float
    delays_hours: Dict[str, float]


class FreightScenarioSet:
    """
    Monte-Carlo scenario generator with stratified + antithetic sampling.

    Stratification splits the unit interval into equal-probability bins so the
    sampled mean converges faster than plain Monte Carlo; antithetic pairing
    mirrors each draw about the mean to cancel first-order bias. The result is
    a stable robustness estimate with far fewer scenarios than naive sampling.
    """

    def __init__(
        self,
        distributions: Sequence[FreightETADistribution],
        n_scenarios: int = 40,
        seed: int = 20260916,
    ) -> None:
        self.distributions = list(distributions)
        self.n_scenarios = max(2, int(n_scenarios))
        self.seed = seed
        self._scenarios: Optional[List[FreightScenario]] = None

    def generate(self) -> List[FreightScenario]:
        if self._scenarios is not None:
            return self._scenarios

        rng = random.Random(self.seed)
        scenarios: List[FreightScenario] = []
        # Each stratum contributes a scenario plus its antithetic mirror, so the
        # set is twice n_scenarios and the weights must normalise over that.
        weight = 1.0 / (2.0 * self.n_scenarios)

        # Stratified probabilities, antithetically paired.
        strata = [
            (i + 0.5) / self.n_scenarios for i in range(self.n_scenarios)
        ]
        mirrored = [1.0 - p for p in strata]

        for idx, p in enumerate(strata):
            delays: Dict[str, float] = {}
            for dist in self.distributions:
                u = rng.uniform(max(1e-6, p - 0.5 / self.n_scenarios),
                                min(1 - 1e-6, p + 0.5 / self.n_scenarios))
                delays[dist.train_id] = _clamp_non_negative(
                    dist.mean_delay_hours
                    + math.sqrt(2.0) * _erfinv(2.0 * u - 1.0) * dist.std_delay_hours
                )
            scenarios.append(FreightScenario(index=idx, weight=weight, delays_hours=delays))

            # Antithetic mirror using the complementary probability.
            mirror_u = mirrored[idx]
            mirror_delays: Dict[str, float] = {}
            for dist in self.distributions:
                mirror_delays[dist.train_id] = _clamp_non_negative(
                    dist.mean_delay_hours
                    + math.sqrt(2.0) * _erfinv(2.0 * mirror_u - 1.0) * dist.std_delay_hours
                )
            scenarios.append(
                FreightScenario(
                    index=self.n_scenarios + idx, weight=weight, delays_hours=mirror_delays
                )
            )

        self._scenarios = scenarios
        return scenarios

    def __len__(self) -> int:
        return len(self.generate())


# ---------------------------------------------------------------------------
# 3. Robust window evaluation
# ---------------------------------------------------------------------------
@dataclass
class WindowRobustness:
    block_id: str
    start_time: float
    end_time: float
    clash_free_probability: float
    expected_delay_hours: float
    worst_case_delay_hours: float
    cvar_delay_hours: float
    scenario_count: int

    @property
    def is_robust(self) -> bool:
        return self.clash_free_probability >= DEFAULT_CONFIDENCE_LEVEL

    def to_dict(self) -> Dict[str, Any]:
        return {
            "block_id": self.block_id,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "clash_free_probability": round(self.clash_free_probability, 4),
            "expected_delay_hours": round(self.expected_delay_hours, 3),
            "worst_case_delay_hours": round(self.worst_case_delay_hours, 3),
            "cvar_delay_hours": round(self.cvar_delay_hours, 3),
            "scenario_count": self.scenario_count,
            "is_robust": self.is_robust,
        }


class RobustWindowEvaluator:
    """
    Scores a candidate maintenance window against the scenario set.

    A "clash" means a train would be physically present on the block while the
    block is under possession. The clash-free probability is the share of
    scenarios in which no train overlaps the window — exactly the spec's "high
    mathematical probability of remaining clash-free".
    """

    def __init__(
        self,
        trains: Sequence[Train],
        distributions: Sequence[FreightETADistribution],
        scenario_set: Optional[FreightScenarioSet] = None,
    ) -> None:
        self.trains = list(trains)
        self.distributions = {d.train_id: d for d in distributions}
        self.scenario_set = scenario_set or FreightScenarioSet(distributions)
        # Pre-compute which trains traverse each block — the spatial join.
        self._block_to_trains: Dict[str, List[Train]] = {}
        for train in self.trains:
            for block_id in train.route:
                self._block_to_trains.setdefault(block_id, []).append(train)

    # -- core ---------------------------------------------------------------
    def _window_delay(
        self,
        block_id: str,
        start: float,
        end: float,
        delays: Dict[str, float],
    ) -> float:
        """Delay hours imposed on traffic by closing ``block_id`` for [start, end)."""
        if end <= start:
            return 0.0
        delay = 0.0
        for train in self._block_to_trains.get(block_id, []):
            shift = float(delays.get(train.id, 0.0))
            t_start = float(train.scheduled_start) + shift
            t_end = float(train.scheduled_end) + shift
            overlap = min(end, t_end) - max(start, t_start)
            if overlap > 0:
                # Premium services carry a heavier operational penalty.
                weight = 2.0 if str(train.category).lower() in (
                    "premium",
                    "vande_bharat",
                    "rajdhani",
                ) else 1.0
                delay += overlap * weight
        return delay

    def evaluate(
        self, block_id: str, start: float, end: float
    ) -> WindowRobustness:
        scenarios = self.scenario_set.generate()
        delays: List[float] = []
        clash_free = 0

        for sc in scenarios:
            d = self._window_delay(block_id, start, end, sc.delays_hours)
            delays.append(d)
            if d <= 0.0:
                clash_free += 1

        n = max(1, len(scenarios))
        expected = sum(d * sc.weight for d, sc in zip(delays, scenarios))
        worst = max(delays) if delays else 0.0
        cvar = self._cvar(delays, DEFAULT_CVAR_ALPHA)

        return WindowRobustness(
            block_id=block_id,
            start_time=start,
            end_time=end,
            clash_free_probability=clash_free / n,
            expected_delay_hours=expected,
            worst_case_delay_hours=worst,
            cvar_delay_hours=cvar,
            scenario_count=len(scenarios),
        )

    @staticmethod
    def _cvar(delays: Sequence[float], alpha: float) -> float:
        """Conditional Value-at-Risk: mean of the worst (1-alpha) tail."""
        if not delays:
            return 0.0
        ordered = sorted(delays, reverse=True)
        tail_len = max(1, int(math.ceil((1.0 - alpha) * len(ordered))))
        return sum(ordered[:tail_len]) / tail_len


# ---------------------------------------------------------------------------
# 4. Whole-schedule analysis
# ---------------------------------------------------------------------------
class StochasticScheduleAnalyzer:
    """Replays a complete schedule across the scenario set."""

    def __init__(self, evaluator: RobustWindowEvaluator) -> None:
        self.evaluator = evaluator

    def analyze(self, schedule: Dict[str, Any]) -> Dict[str, Any]:
        jobs = schedule.get("scheduled_jobs", [])
        per_job: List[Dict[str, Any]] = []
        total_expected = 0.0
        robust_count = 0

        for job in jobs:
            rob = self.evaluator.evaluate(
                job["block_id"], float(job["start_time"]), float(job["end_time"])
            )
            total_expected += rob.expected_delay_hours
            if rob.is_robust:
                robust_count += 1
            per_job.append(
                {
                    "job_id": job.get("job_id"),
                    "block_id": rob.block_id,
                    "start_time": rob.start_time,
                    "end_time": rob.end_time,
                    "clash_free_probability": round(rob.clash_free_probability, 4),
                    "expected_delay_hours": round(rob.expected_delay_hours, 3),
                    "is_robust": rob.is_robust,
                }
            )

        n_jobs = max(1, len(jobs))
        return {
            "scenario_count": len(self.evaluator.scenario_set),
            "expected_delay_hours": round(total_expected, 3),
            "robust_job_count": robust_count,
            "robust_fraction": round(robust_count / n_jobs, 4),
            "per_job": per_job,
        }


# ---------------------------------------------------------------------------
# 5. Robust window optimiser (Stochastic Integer Programming step)
# ---------------------------------------------------------------------------
class RobustWindowOptimizer:
    """
    Chooses integer start times that maximise robustness under ETA uncertainty.

    This is the stochastic integer programming step: decision variables are
    integral start hours; feasibility is the resource/closure envelope; the
    objective trades clash-free probability against expected delay.
    """

    def __init__(
        self,
        evaluator: RobustWindowEvaluator,
        horizon_hours: int = 24,
        confidence_level: float = DEFAULT_CONFIDENCE_LEVEL,
    ) -> None:
        self.evaluator = evaluator
        self.horizon_hours = horizon_hours
        self.confidence_level = confidence_level

    def best_window(
        self,
        block_id: str,
        duration: float,
        forbidden: Optional[Iterable[Tuple[float, float]]] = None,
        fixed_start: Optional[float] = None,
    ) -> Optional[WindowRobustness]:
        """
        Search integral start times for the most robust window of ``duration``.

        ``forbidden`` is a list of (start, end) intervals already occupied —
        e.g. frozen Week-1 possessions or emergency blocks.
        """
        if fixed_start is not None:
            rob = self.evaluator.evaluate(
                block_id, float(fixed_start), float(fixed_start) + duration
            )
            return rob

        blocked = list(forbidden or [])
        duration = float(duration)
        last_start = int(self.horizon_hours - math.ceil(duration))
        if last_start < 0:
            return None

        best: Optional[WindowRobustness] = None
        for start in range(0, last_start + 1):
            end = start + duration
            if any(start < f_end and end > f_start for f_start, f_end in blocked):
                continue
            rob = self.evaluator.evaluate(block_id, float(start), end)
            if best is None or self._better(rob, best):
                best = rob

        return best

    def _better(self, candidate: WindowRobustness, incumbent: WindowRobustness) -> bool:
        """
        Lexicographic objective: first satisfy the confidence level, then
        minimise expected delay, then worst case.
        """
        c_ok = candidate.clash_free_probability >= self.confidence_level
        i_ok = incumbent.clash_free_probability >= self.confidence_level
        if c_ok != i_ok:
            return c_ok
        if not math.isclose(
            candidate.expected_delay_hours, incumbent.expected_delay_hours, rel_tol=1e-9
        ):
            return candidate.expected_delay_hours < incumbent.expected_delay_hours
        return candidate.worst_case_delay_hours < incumbent.worst_case_delay_hours

    def repair_schedule(
        self,
        schedule: Dict[str, Any],
        scenario: Scenario,
    ) -> Dict[str, Any]:
        """
        Re-time non-frozen jobs onto their most robust feasible window.

        Frozen / fixed jobs are left untouched — that is the whole point of the
        Week-1 freeze, and violating it would break the possession-immutability
        safety invariant.
        """
        repaired = dict(schedule)
        fixed_lookup = {j.id: j for j in scenario.jobs}
        occupied: Dict[str, List[Tuple[float, float]]] = {}

        for fb in scenario.fixed_blocks:
            occupied.setdefault(fb.block_id, []).append(
                (float(fb.start_time), float(fb.end_time))
            )

        new_jobs: List[Dict[str, Any]] = []
        moved: List[Dict[str, Any]] = []

        for job in schedule.get("scheduled_jobs", []):
            original = fixed_lookup.get(job.get("job_id"))
            duration = float(job["end_time"]) - float(job["start_time"])
            if duration <= 0:
                new_jobs.append(job)
                continue

            is_immutable = bool(
                original is not None
                and getattr(original, "is_fixed", False)
                and getattr(original, "fixed_start", None) is not None
            )

            if is_immutable:
                new_jobs.append(job)
                occupied.setdefault(job["block_id"], []).append(
                    (float(job["start_time"]), float(job["end_time"]))
                )
                continue

            best = self.best_window(
                block_id=job["block_id"],
                duration=duration,
                forbidden=occupied.get(job["block_id"], []),
            )
            if best is None:
                new_jobs.append(job)
                occupied.setdefault(job["block_id"], []).append(
                    (float(job["start_time"]), float(job["end_time"]))
                )
                continue

            if not math.isclose(best.start_time, float(job["start_time"]), rel_tol=1e-9):
                moved.append(
                    {
                        "job_id": job.get("job_id"),
                        "block_id": job["block_id"],
                        "old_start": float(job["start_time"]),
                        "new_start": best.start_time,
                        "clash_free_probability": round(best.clash_free_probability, 4),
                        "old_clash_free_probability": round(
                            self.evaluator.evaluate(
                                job["block_id"],
                                float(job["start_time"]),
                                float(job["end_time"]),
                            ).clash_free_probability,
                            4,
                        ),
                    }
                )

            updated = dict(job)
            updated["start_time"] = best.start_time
            updated["end_time"] = best.start_time + duration
            new_jobs.append(updated)
            occupied.setdefault(job["block_id"], []).append(
                (best.start_time, best.start_time + duration)
            )

        repaired["scheduled_jobs"] = new_jobs
        repaired["stochastic_repairs"] = moved
        return repaired


# ---------------------------------------------------------------------------
# Convenience factory
# ---------------------------------------------------------------------------
def build_stochastic_pipeline(
    scenario: Scenario,
    history: Optional[Dict[str, Sequence[float]]] = None,
    n_scenarios: int = 40,
    seed: int = 20260916,
    horizon_hours: int = 24,
    confidence_level: float = DEFAULT_CONFIDENCE_LEVEL,
) -> Tuple[RobustWindowEvaluator, RobustWindowOptimizer, StochasticScheduleAnalyzer]:
    """One-call construction of the full stochastic stack for a scenario."""
    history = history or {}
    distributions = [
        FreightETADistribution.from_history(train, history.get(train.id))
        for train in scenario.trains
    ]
    scenario_set = FreightScenarioSet(distributions, n_scenarios=n_scenarios, seed=seed)
    evaluator = RobustWindowEvaluator(scenario.trains, distributions, scenario_set)
    optimizer = RobustWindowOptimizer(
        evaluator, horizon_hours=horizon_hours, confidence_level=confidence_level
    )
    analyzer = StochasticScheduleAnalyzer(evaluator)
    return evaluator, optimizer, analyzer
